# Generated by Django 5.1.4 on 2024-12-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books",
            name="publish_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
